# Generated by Django 5.0.4 on 2024-04-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=55)),
                ('duracao', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=55)),
                ('cpf', models.CharField(max_length=11, unique='True')),
                ('rg', models.CharField(max_length=9, unique='True')),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=55, unique='True')),
                ('telefone', models.CharField(max_length=14, unique='True')),
                ('endereco', models.CharField(max_length=55)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(max_length=55)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.professor')),
            ],
        ),
    ]
