# Generated by Django 5.0.4 on 2024-04-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='nome_turma',
            new_name='nome',
        ),
    ]
