# Generated by Django 5.0.4 on 2024-04-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_rename_nome_turma_turma_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDaSemana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoraDoDia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracao',
        ),
    ]
