# Generated by Django 5.0.4 on 2024-04-30 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_diadasemana_horadodia_remove_curso_duracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='diadasemana',
            options={'verbose_name_plural': 'Dias Da Semana'},
        ),
        migrations.AlterModelOptions(
            name='horadodia',
            options={'verbose_name_plural': 'Horas Do Dia'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name_plural': 'Turmas'},
        ),
        migrations.CreateModel(
            name='CargaHorariaProfessor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_da_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.diadasemana')),
                ('horas_do_dia', models.ManyToManyField(to='gerenciamento.horadodia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.professor')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='carga_horaria_semanal',
            field=models.ManyToManyField(related_name='carga_horaria_professores', through='gerenciamento.CargaHorariaProfessor', to='gerenciamento.diadasemana'),
        ),
        migrations.CreateModel(
            name='CargaHorariaTurma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_da_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.diadasemana')),
                ('horas_do_dia', models.ManyToManyField(to='gerenciamento.horadodia')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.turma')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='carga_horaria_semanal',
            field=models.ManyToManyField(related_name='carga_horaria_turmas', through='gerenciamento.CargaHorariaTurma', to='gerenciamento.diadasemana'),
        ),
    ]
