# Generated by Django 5.0.4 on 2024-04-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_alter_curso_options_alter_diadasemana_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ManyToManyField(to='gerenciamento.professor'),
        ),
    ]
