# Generated by Django 5.0.4 on 2024-04-30 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_remove_turma_professor_turma_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diadasemana',
            options={'verbose_name_plural': 'Dias da Semana'},
        ),
        migrations.AlterModelOptions(
            name='horadodia',
            options={'verbose_name_plural': 'Horas do Dia'},
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
