# Generated by Django 5.0.4 on 2024-05-01 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0006_alter_diadasemana_options_alter_horadodia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargahorariaprofessor',
            options={'verbose_name_plural': 'Carga Horária dos Professores'},
        ),
        migrations.AlterModelOptions(
            name='cargahorariaturma',
            options={'verbose_name_plural': 'Carga Horária das Turmas'},
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ManyToManyField(blank=True, to='gerenciamento.professor'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=55)),
                ('cpf', models.CharField(max_length=11, unique='True')),
                ('rg', models.CharField(max_length=9, unique='True')),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=55, unique='True')),
                ('telefone', models.CharField(max_length=14, unique='True')),
                ('endereco', models.CharField(max_length=55)),
                ('data_matricula', models.DateField()),
                ('situacao_matricula', models.BooleanField()),
                ('curso', models.ManyToManyField(to='gerenciamento.curso')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
