# Generated by Django 5.0.4 on 2024-05-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0009_aluno_turma_alter_aluno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=55)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.curso')),
                ('dia_da_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.diadasemana')),
                ('hora_do_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.horadodia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.turma')),
            ],
            options={
                'verbose_name_plural': 'Aulas',
            },
        ),
    ]
