# Generated by Django 5.0.4 on 2024-05-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0010_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='nome',
        ),
    ]
