# Generated by Django 5.0.4 on 2024-05-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0018_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='assunto',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
